### ISSUE TITLE
World Reload bug

### ISSUE THREAD

**Issue by LokyLive** [Team-RTG/Lonely-Biome#11]
When i create a new map my selected biome for world generation works fine but when i quit and reload the map, if i walk a bit to find new zone , vanilla worldgen appear 

Forge version : 23.5.2821
Lonely biome version : 2.0.0

cfg file : 
https://paste.dimdev.org/oqizarisot.bash

![biome](https://user-images.githubusercontent.com/15186174/54530089-16e20c80-4982-11e9-88dd-f38a38e16ece.jpg)

**Comment by srs-bsns** [comment]
fixed in ad83b15e69707ab3ca028cc4dad605377dd57c7f
