### ISSUE TITLE
[Suggestion] Storing biomeID in world itself instead of config

### ISSUE THREAD

**Issue by donqixot** [Team-RTG/Lonely-Biome#5]
Great mod, thank you! Very useful.

Right now, if I create 2 different worlds with different biomeIDs, in order to switch between them, I need to modify config, otherwise new chunks will be created with biomeID from config, which may be different than the world biomeID. If there was a way to store biomeID in the world itself, then config could be used only for initial world creation, but existing world new chunks can be generated using stored biomeID of the loaded world. That would allow switching between worlds safe and easy. Right now, it is very easy for forget to change config back to -1.

Of course, even better option would be to have world type option just like RTG has where you can specify biomeID :)

**Comment by srs-bsns** [comment]
No longer relevant.
