### ISSUE TITLE
lonely biomes everywhere

### ISSUE THREAD

**Issue by superon** [Team-RTG/Lonely-Biome#6]
lonely biome appears to be overwriting every planet in Advanced Rocketry with the same single biome.
does Lonely Biome have a "type" for dim mapping? re: 
<planet name="Earth" DIMID="0" dimMapping="">

**Comment by superckl** [comment]
Lonely Biome uses GenLayers to to do it's override. I don't think any dimension information is provided in those events, so this might be a tricky one to solve. Is there a reason gen layers are used rather than a new WorldType, @whichonespink44 ?

**Comment by srs-bsns** [comment]
That is correct. `WorldTypeEvent.InitBiomeGens` is used to set the biome GenLayer and there is no world-specific context in that event. The only restriction that can be made is by `WorldType`, which we should be doing (Overworld type only), though we aren't. That doesn't solve the issue though.

When LonelyBiome was written it was made mostly as a development tool and wasn't designed to be used in serious gameplay. But, I've never been happy with the restrictions of it, so I might try to fix some issue like this in the future, once RTG is less of a priority.

The best solution I can think of, right now, would be to alter a world's GenLayer at the earliest possible time before the server starts by manually setting the `genBiomes` and `biomeIndexLayer` fields in the `WorldProvider`'s `BiomeProvider` instance. Those fields are private though, so using reflection, or an access transformer, will be required. Config settings for a whitelist/blacklist can be used to restrict what dimensions can/cannot be single-biome.

**Comment by superon** [comment]
1.7.10 btw

**Comment by superon** [comment]
oh hey, i've just seen these replies, thanks for posting but i gotta say i don't understand what you're saying:/  the fault is no doubt at my end bc i'm really quite useless when it comes to coder chat, which i can only assume that was, l'll keep bushing the buttons and see if i can hit the right combination:)

**Comment by srs-bsns** [comment]
No longer relevant.
